### ISSUE TITLE
If files external is not activated inotify throws an error 500 and breaks nextcloud

### ISSUE THREAD

**Issue by small1** [icewind1991/files_inotify#10]
Using nextcloud 15.0.5 and installed files_inotify 0.1.3 on debian 9.

Steps to reproduce:
1. deactivate external storage support
2. install inotify file watcher
3. get an error 500

What i would expect
1. deactivate external storage support
2. install inotify file watcher 
3. get an error message that it could not be activated since external storage support is deactivated

From the nginx error log:

2019/03/14 13:12:21 [error] 906#906: *69459 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Interface 'OCA\Files_External\Lib\Config\IBackendProvider' not found in /var/www/nextcloud/apps/files_inotify/lib/AppInfo/Application.php on line 29" while reading response header from upstream, client: X.X.X.X, server: cloud.adomain.test, request: "GET /apps/files/ HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "cloud.adomain.test"

**Comment by Notmarrco** [comment]
Issue still there in nextcloud 20 on debian 10.

```
Error: Interface 'OCA\Files_External\Lib\Config\IBackendProvider' not found in /nextcloud/apps/files_inotify/lib/AppInfo/Application.php:29
Stack trace:
#0 /nextcloud/lib/composer/composer/ClassLoader.php(444): include()
#1 /nextcloud/lib/composer/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 [internal function]: spl_autoload_call()
#4 /nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php(108): class_exists()
#5 /nextcloud/lib/base.php(644): OC\AppFramework\Bootstrap\Coordinator->runRegistration()
#6 /nextcloud/lib/base.php(1091): OC::init()
#7 /nextcloud/console.php(49): require_once('...')
#8 /nextcloud/occ(11): require_once('...')
#9 {main}
```

workaround : Remove `apps/file_inotify` directory, then install the external storage application.
